gogf/gf

g/net/ghttp/ghttp_func.go
This function was originally forced to Url encoding, sometimes not needed; now add a parameter to enhance the flexibility of the function. When the new parameter has no value, the function is the same as before.
=> function BuildParams add 'UnUrlEncode' param, default false.

util/gvalid/gvalid_check.go, util/gvalid/gvalid_message.go, util/gvalid/gvalid_unit_basic_all_test.go
1、修改身份证尾数验证规则，原先的未做末尾数字规则校验
2、新增银行卡号验证规则（LuHn算法规则）
注：第一次使用github，代码中间肯定有不足，本人英语水平不好，还请见谅。
=> 修改身份证尾数验证规则,新增银行卡号验证规则

net/ghttp/ghttp_client_request.go
Get ghttp client a chance to add custom host in header. Golang can only set host with Request while it seems that there is not a possible way to add a custom host to a http request.
=> Get ghttp a chance to add custom host.

text/gstr/gstr_case.go, text/gstr/gstr_z_unit_case_test.go
为了实现数据库字段优雅映射为实体类，如`md5`应映射为 `Md5`, 新增一个`不连续大写字母首位加下划线`的方法。
Fix #795 
```
{"RGBCodeMd5", "rgb_code_md5"},
{"testCase", "test_case"},
{"Md5", "md5"},
{"userID", "user_id"},
{"RGB", "rgb"},
{"RGBCode", "rgb_code"},
{"_ID", "id"},
{"User_ID", "user_id"},
{"user_id", "user_id"},
{"md5", "md5"},
``
=> 驼峰转换下划线时，不连续大写字母首位加下划线规范

os/gtimer/gtimer.go, os/gtimer/gtimer_entry.go, os/gtimer/gtimer_loop.go, os/gtimer/gtimer_z_unit_1_test.go
Test Code:
~~~
glog.Printf("start time:%d", time.Now().Unix())
singleton := timer.AddSingleton(2*time.Second, func() {
glog.Println(time.Now().Unix())
})
time.Sleep(5 * time.Second)
glog.Printf("reset time:%d", time.Now().Unix())
singleton.Reset()
select {}
~~~
Test results:
~~~
=== RUN   TestTimer_Reset
2020-07-29 10:29:36.129 start time:1595989776
2020-07-29 10:29:38.138 1595989778
2020-07-29 10:29:40.118 1595989780
2020-07-29 10:29:41.165 reset time:1595989781
2020-07-29 10:29:43.358 1595989783
2020-07-29 10:29:45.338 1595989785
2020-07-29 10:29:47.318 1595989787
2020-07-29 10:29:49.298 1595989789
~~~
=> add func gtimer.Entry.Reset()

database/gdb/gdb.go, database/gdb/gdb_core.go
=> 修改sql打印debug信息，增加数据库配置的group名称，用于区分sql来源，尤其是多数据库配置的时候

encoding/gjson/gjson_api_new_load.go, os/gcfg/gcfg_z_unit_test.go, os/gcfg/testdata/cfg-with-utf8-bom.toml
解决 #787
由于在Windows下修改配置文件导致配置文件带UTF8-BOM,产生异常错误的问题
=> fix configfile with UTF8-BOM issue

os/gcmd/gcmd_scan.go
变更内容：
gcmd.Scan支持包含空格的整行输入 #824 
另外看了下gcmd.Scanf目前有些问题，此用法并非Scanf本意
但如果在fmt.Scanf上封装仅多个prompt，觉得又很鸡肋，所以建议去掉这个方法以免与fmt.Scanf混淆， @gqcn 你看呢
=> gcmd.Scan supports read line that contains whitespace

net/ghttp/ghttp_request.go, net/ghttp/ghttp_unit_param_test.go
sometimes, we want to modify request parameters through middleware, but directly modifying `Request.Body` is invalid, so I add function `ReloadParam` for `ghttp_request.go` to clear parsed* mark.
```go
func MiddlewareExample(r *ghttp.Request) {
// ... this is newParam
r.Request.Body = ioutil.NopCloser(bytes.NewReader(newParam))
r.ReloadParam()
r.Middleware.Next()
}
```
=> Solve the problem of invalid modification of request parameters

encoding/gjson/gjson_api_new_load.go
Make it work when the xml content has ` `,`\n`,`\r` or `\t` in the end. 
The json content can work well when the content not end with `}`, I think xml should not be too strict.
=> Update gjson_api_new_load.go to make gjson work when sometimes the xml end with space or `\n`

container/gpool/gpool.go
在Pool.Get函数中发现PoolItem过期后，直接丢弃，没有调用过期的回调函数，可能导致外部逻辑异常。既然提供了过期回调，此处理应调用过期回调函数。
=> Not Callback ExpireFunc In Pool.Get()

net/ghttp/ghttp_server_util.go, net/ghttp/ghttp_unit_server_util_test.go
将标准库的 HandlerFunc 和 Handler 转换为 ghttp.HandlerFunc，使得 ghttp 的 server 可以复用开源社区中标准库的中间件
参考 [gin 的实现](https://github.com/gin-gonic/gin/blob/master/utils.go#L38)
如复用标准库的cors
```go
import (
"github.com/gogf/gf/net/ghttp"
"github.com/rs/cors"
)
func main() {
s := g.Server(p)
c := cors.Default()
server.Use(ghttp.WrapH(c))
server.Use(ghttp.WrapF(c.HandlerFunc))
}
```
=> add util: WrapF and WrapH to transform net/http handler to ghttp.HandlerFunc

os/gtime/gtime_format.go
when day is 21，abbreviated as 21st，suffix is st ,is not th
when day is 22，abbreviated as 22nd，suffix is nd ,is not th
when day is 23，abbreviated as 23rd，suffix is rd ,is not th
when day is 31，abbreviated as 31st，suffix is st ,is not th
=> formatMonthDaySuffixMap() misjudged suffix

database/gdb/gdb_core.go
该取消函数会导致设置QueryTimeout后通过gdb拿到的数据不完整。因为函数退出的时候关闭了rowsi的mysqlConn。
=> 去除cancelFunc避免退出之前关闭mysqlConn导致数据获取不完整

database/gdb/gdb_core_config.go, database/gdb/gdb_driver_mysql.go, database/gdb/gdb_driver_pgsql.go
由于gdb在格式化SQL时，gtime.Time类型为Y-m-d H:i:s，不带时区，此时如果数据库时区和程序的不一致，就会导致存入的时间丢时区。
所以gdb配置增加了timezone，可以在连接数据库时指定时区，避免以上问题
=> add timezone configuration for package gdb

util/gutil/gutil_slice.go, util/gutil/gutil_z_unit_slice_test.go
增加gutil.SliceToMapWithColumnAsKey方法
把struct slice或者map slice，指定一列的值作为key，生成一个map
例如
```go
package main
import (
"github.com/gogf/gf/frame/g"
"github.com/gogf/gf/util/gutil"
)
type data struct {
ID   int
Name string
}
func main() {
d1 := &data{1, "a"}
d2 := &data{2, "b"}
d3 := &data{3, "c"}
d := []*data{d1, d2, d3}
res := gutil.SliceToMapWithColumnAsKey(d, "ID")
g.Log().Debugf("res: %#v", res[1])
g.Log().Debugf("res: %#v", res[1].(*data).Name)
res2 := gutil.SliceToMapWithColumnAsKey(d, "Name")
g.Log().Debugf("res2: %#v", res2["b"])
g.Log().Debugf("res2: %#v", res2["b"].(*data).Name)
m1 := g.Map{"id": 1, "name": "a"}
m2 := g.Map{"id": 2, "name": "b"}
m3 := g.Map{"id": 3, "name": "c"}
m := []g.Map{m1, m2, m3}
res3 := gutil.SliceToMapWithColumnAsKey(m, "id")
g.Log().Debugf("res3: %#v", …
```
=> add gutil.SliceToMapWithColumnAsKey

.example/net/gtcp/gtcp_conn.go
原来的demo获取的content-length不正确，并且[]byte最后一位为\r，需要去除
=> fix tcp http demo error content-length

encoding/gini/gini.go, encoding/gini/gini_test.go
=> 修复gini组件不能正确获取带“=”值的Bug

database/gdb/gdb_func.go, database/gdb/gdb_z_mysql_model_test.go
issue: [https://github.com/gogf/gf/pull/1498](https://github.com/gogf/gf/pull/1498)
=> order by null is not escaped

database/gdb/gdb_core_tracing.go, net/gtrace/gtrace.go
Tip: the statistics of SQL data are based on Tagkey db.statement and db.instance, for example: tracer.activeSpan () .setTag ("db.statement", "SELECT * FROM wuser_table"); see [the Span Tag specification of OpenTracing ](https://github.com/opentracing-contrib/opentracing-specification-zh/blob/master/semantic_conventions.md)
=> feat:add trace db.statement、host.name

text/gstr/gstr_domain.go
Fix a comment error in IsSubDomain.
=> fix a comment error in IsSubDomain

net/ghttp/ghttp_request.go, net/ghttp/ghttp_z_unit_feature_ip_test.go
- IPv6 address only use square bracket when  in conjunction with other parts such as user:pass and :port.
- Literal IPv6 addresses with square bracket can't be parsed by Golang offical `net.ParseIP`,.As the name `GetRemoteIp ` ,we just want a parsable IP,not the literal form in URI.
- IPv6地址只有在与其他部分（如user:pass和:port）结合时才使用方括号。
- 带有方括号的IPv6地址不能被Golang官方的`net.ParseIP`解析。一个可解析的IPv6地址，不应该包含只URI中出现的，为了防止歧义使用的方括号。
=> ghttp_request.go GetRemoteIp ipv6 fix

database/gdb/gdb_driver_pgsql.go
变更内容：
pgsql驱动TableFields方法，查询SQL增加attisdropped条件
变更原因：
pgsql在删除字段后，TableFields方法没加过滤条件，仍可获取到一个dropped字段名，导致之后的SQL全部执行失败
[attisdropped字段说明](https://www.postgresql.org/docs/14/catalog-pg-attribute.html)
=> gdb pgsql skip dropped fields

database/gdb/gdb_model_select.go
=> 修改gdb cache的key为gcache:md5(sql)方式

database/gdb/gdb_model_order_group.go, database/gdb/gdb_z_mysql_model_test.go
```
if model.orderBy != "" {
model.orderBy += ","
}
```
既然前边已经有了这样的判断，说明Order方法本意是允许多次调用`.OrderDesc("a").OrderDesc("b")`来生成类似于`order by a desc, b desc`这样的查询语句的，所以这里应该使用`+=`而不是`=`
=> Fix gdb Order

net/ghttp/ghttp_server_swagger.go
Resolve the js link when there are parameters on the url
=> fix: js link err

net/ghttp/ghttp_request_param_request.go
[fix bug] the default value of r.get is invalid
重跑ci
=> [fix bug] the default value of r.get is invalid

net/ghttp/ghttp_server.go, net/ghttp/ghttp_server_config.go, net/ghttp/ghttp_server_graceful.go, net/ghttp/ghttp_z_unit_feature_config_test.go, net/ghttp/ghttp_z_unit_feature_custom_listeners_test.go
Add SetListener method for supporting custom listeners.
```go
// 设置单个listener
ln, err := net.Listen("tcp", ":8199")
if err != nil {
log.Fatal(err)
}
....
s := g.Server()
s.SetListener(ln)
...
s.Run()
```
```go
// 设置多个listener
ln1, err := net.Listen("tcp", ":8199")
if err != nil {
log.Fatal(err)
}
ln2, err := net.Listen("tcp", ":8299")
if err != nil {
log.Fatal(err)
}
....
s := g.Server()
s.SetListener(ln1, ln2)
...
s.Run()
```
另外有相关的issue
https://github.com/gogf/gf/issues/1043
=> feat: support custom listener

protocol/goai/goai.go, protocol/goai/goai_parameter_ref.go, protocol/goai/goai_shema.go, protocol/goai/goai_shemas.go, protocol/goai/goai_z_unit_test.go
=> fix: swagger ignore "-" param.

os/gcfg/gcfg_adapter_file.go
dataType := gfile.ExtName(usedFileName) usedFileName is always "config" and dataType is "",usedFileName should be filePath instead.
Add support for properties config file.
=> Bug fix#1849

net/ghttp/ghttp_server_swagger.go
The jsdelivr cdn certificate expired in the mainland, causing the website to hang. To fix it, the solution is to replace the CDN source to unpkg.com
=> Replace the Swagger JS CDN source from jsdelivr to unpkg.com

database/gdb/gdb_model_order_group.go
Fix multiple gdb-group overrides
=> Fix multiple gdb-group overrides

cmd/gf/internal/consts/consts_gen_dao_template_dao.go, contrib/drivers/pgsql/pgsql.go
pgsql列出表名方法更新，不再返回partition子表名
```sql
drop table if exists test_partition;
CREATE TABLE test_partition (                                
id int8
)                                
PARTITION BY HASH (id);                                
CREATE TABLE "test_partition_p0" PARTITION OF "public"."test_partition" FOR VALUES WITH(MODULUS 50, REMAINDER 0);
CREATE TABLE "test_partition_p1" PARTITION OF "public"."test_partition" FOR VALUES WITH(MODULUS 50, REMAINDER 1);
CREATE TABLE "test_partition_p2" PARTITION OF "public"."test_partition" FOR VALUES WITH(MODULUS 50, REMAINDER 2);
```
```sql
SELECT TABLENAME FROM PG_TABLES WHERE SCHEMANAME = 'public' ORDER BY TABLENAME
```
返回结果
```
test_partition
test_partition_p0
test_partition_p1
test_partition_p2
```
```sql
SELECT
c.relname
FROM
pg_class c
INNER …
```
=> improve list tables for pgsql

database/gdb/gdb.go
see https://github.com/gogf/gf/issues/1996
修复了部分地方没有用 RW 锁导致的竞争 panic
=> fix(gdb): panic when concurrent db config map read and write.

cmd/gf/internal/cmd/gendao/gendao.go
`gf-cli` 's command `gen dao` 's brief of `noJsonTag` in the input structure is missing a `}` , which leads to some flaws in `gen dao` 's help information
=> fix gf-cli command 'gen dao' help infomation

encoding/gjson/gjson_api_new_load.go, encoding/gjson/gjson_z_unit_feature_new_test.go
=> fix precision lost of int64 for package gcfg

cmd/gf/internal/cmd/gendao/gendao_structure.go, contrib/drivers/pgsql/pgsql.go, database/gdb/gdb_func_structure.go
修复当前版本生成entity时，int8和json类型字段都无法正确解析到本地类型的问题
另外数据库的int4类型是32位，调整了一下转换成了 int
=> improve gdb.CheckValueForLocalType for pgsql

os/gctx/gctx.go
https://github.com/gogf/gf/issues/2039
=> fix gctx init slice bounds out of range on  ios platform

contrib/drivers/clickhouse/clickhouse.go, contrib/drivers/clickhouse/clickhouse_test.go
场景：`gf gen dao`
在gen dao时，只有`link` , `d.GetConfig().Name`始终为空。
=> fix (clickhouse) : 修复clickhouse 使用link链接时 TableFields 

util/gconv/gconv_int.go, util/gconv/gconv_uint.go, util/gconv/gconv_z_unit_all_test.go
Mainly include the following changes
- When using gconv.Int64/gconv.Uint64 , if the result is NaN, it will become 0
- When using gconv.Float64 / gconv.Float32 , if the result is NaN, it will not be modified
Fix the change only occurs when floating point to uint/int
=> fixed inconsistent results when converting float64(NaN) to int/uint on multiple platforms

database/gdb/gdb_driver_wrapper_db.go, database/gdb/gdb_model_utility.go
=> fix issue #1965

contrib/drivers/pgsql/pgsql.go
由于驱动内类型检查函数名错误，导致未能使用正确类型生成 entry 模型
=> fix: pgsql driver check local type error

net/ghttp/ghttp_server_service_handler.go, os/gcmd/gcmd_command_object.go
Checking concrete implementation interfaces is more rigorous than strings
=> opt: parameter verification of optimized handler methods

text/gstr/gstr_domain.go, text/gstr/gstr_z_unit_domain_test.go
```
package gstr
func IsSubDomain(subDomain string, mainDomain string) bool {
...
}
```
function 'IsSubDomain' has an error:
`gstr.IsSubDomain("goframe.org", "s.goframe.org") ` return true, I think it should return false
This PR to fix it
=> fix IsSubDomain method error

contrib/drivers/clickhouse/clickhouse_test.go
原来的测试中的SQL语句可读性太差，有的没有缩进，贴着左边，有的又缩进了三个tab。
The SQL statements in the original test were  not readable .
我统一了缩进格式。
I unified the indentation format.
=> style(test): Unify the indentation format of SQL strings in clickhouse_test

net/ghttp/ghttp_request_param_request.go, net/ghttp/ghttp_z_unit_feature_request_file_test.go, util/gconv/gconv_struct.go
Merged and improved from https://github.com/gogf/gf/pull/2357
=> fix issue when only one file was uploaded in batch receiver attribute

net/ghttp/ghttp_server_config_static.go, net/ghttp/ghttp_server_handler.go
https://github.com/gogf/gf/issues/2333
静态文件服务的对象字段非公开导致无法通过配置文件进行配置
=> fix: ghttp server static path config

.github/workflows/gf.yml
=> improve ci by using cache feature of `setup-go`

container/garray/garray_sorted_any.go, container/garray/garray_sorted_int.go, container/garray/garray_sorted_str.go
When multiple gouroutines are trying to remove values from the same garray. After one routine calculate the index to remove, the other one could have removed the value before the calculated index, causing the index to shift and remove the wrong element. Making both the search and remove action atomic solve this problem.
=> Protect RemoveValue from race condition

contrib/nosql/redis/redis.go, database/gredis/gredis.go
- maxActive没生效
- redis adapter初始化了两次
=> fix: gredis maxActive config and duplicate connection bug

os/gtimer/gtimer.go, os/gtimer/gtimer_timer.go, os/gtimer/gtimer_z_unit_entry_test.go, os/gtimer/gtimer_z_unit_timer_test.go
This commit adds a new `Quick` bool to the timer code, which can be used to set the timer to quickly run without waiting for the first interval to be elapsed. This can be useful in certain scenarios where time-sensitive operations need to be performed immediately. 
此提交向 gtimer 添加了一个新的“Quick”布尔值，可用于将计时器设置为添加任务后立即执行，而无需等待第一个间隔结束。 这在某些需要立即执行时间敏感操作的场景中很有用。
PS：现在假设我添加一个30分钟执行的任务，则需要30分钟后才能第一次执行！
=> add `Quick`  mode for gtimer

net/ghttp/ghttp_server_admin_unix.go
当用户没有开启优雅重启选项(`graceful: true`)时, gf不会创建pid和port的映射文件, 所以如果用户通过 `kill -SIGUSR1 pid` 来重启服务, 当产生子进程后, 父进程不会退出. 不过通过`http://localhost:8000/debug/admin/restart` api来重启, 不会有这个问题, 因为gf不会重启, 只会响应 `graceful reload feature is disabled` 提示用户.
这个pl就是解决此种场景下用户通过 `kill -SIGUSR1 pid`重启服务导致的问题, 优化后的效果:
如果没有开启优雅重启, 服务接收到`SIGUSR1`信号后, 不会重启, 只会打印警告日志: 
`2023-03-21 10:35:17.292 [WARN] graceful reload feature is disabled`
=> optimize the handling of the `SIGUSR1` signal

contrib/drivers/mysql/mysql_feature_model_builder_test.go, database/gdb/gdb_model_builder.go
getBuilder creates and returns a cloned WhereBuilder of current WhereBuilder if `safe` is true,
or else it returns the current WhereBuilder.
But it seems that getBuilder directly returns b.Clone()
=> comment updates for gdb.Builder

contrib/registry/file/file.go, contrib/registry/file/file_discovery.go, contrib/registry/file/file_registrar.go, net/gsvc/gsvc.go, net/gsvc/gsvc_endpoint.go
=> fix file registry that not works on windows

contrib/drivers/sqlite/sqlite_model_test.go, database/gdb/gdb_model_select.go
feat: 添加方法两个 ScanAndCount, AllAndCount.
=> add method `ScanAndCount` and `AllAndCount` for Model package `gdb`

cmd/gf/internal/cmd/gendao/gendao.go, cmd/gf/internal/cmd/gendao/gendao_do.go, cmd/gf/internal/cmd/gendao/gendao_entity.go, cmd/gf/internal/cmd/gendao/gendao_structure.go, cmd/gf/internal/utility/utils/utils.go, cmd/gf/internal/utility/utils/utils_test.go, contrib/drivers/mssql/mssql_z_model_test.go, contrib/drivers/mysql/mysql_model_test.go, contrib/drivers/sqlite/sqlite_model_test.go, database/gdb/gdb.go, database/gdb/gdb_core_structure.go, database/gdb/gdb_func.go
improved from pr https://github.com/gogf/gf/pull/2656
=> add type mapping feature for command `gf gen dao`

contrib/drivers/mysql/mysql_basic_test.go, contrib/drivers/mysql/mysql_core_test.go, database/gdb/gdb_core_structure.go, database/gdb/gdb_func.go
```go
// iString is the type assert api for String.
type iString interface {
String() string
}
// iNil if the type assert api for IsNil.
type iNil interface {
IsNil() bool
}
```
check whether `value` implements the `iNil` interface, before `iString` interface.
fix issue in converting `gjson.New('')` and `gjson.New(nil)` to `nil`, related Issues: #2719
=> fix issue in converting value to nil when calling IsNil return ture for gdb.Core

net/ghttp/ghttp_server.go, net/ghttp/ghttp_z_unit_test.go
=> fix g.Wait not support OS Signal #2752

cmd/gf/internal/cmd/genctrl/genctrl_generate_sdk.go, cmd/gf/internal/consts/consts_gen_ctrl_template_sdk.go
Fix the issue that `api/sdk/sdk.iclient.go` generated by `gf gen ctrl -k api/sdk` miss some content.
Fixes #2816.
=> fix issue #2816

contrib/sdk/httpclient/httpclient.go
用户在使用`sdk/httpclient`的时候可能忽略或忘记定制http客户端, 此时应该为其提供一个默认的http客户端实例(`gclient.New()`), 否则程序将会异常退出.
=> refactor: add default client instance for contrib/sdk/httpclient

net/goai/goai_path.go, net/goai/goai_z_unit_test.go
因为当前 tag 都是针对 Operation 对象设置的，不应该将 Operation 的 summary 和 description 直接添加到 PathItem 。
如存在`POST /user`的 summary 为`新增用户`，存在`DELETE /user`的 summary 为`删除用户`，两者为相反操作，其 PathItem 的 summary 应当留空而不是使用其中一个。
实际测试：
```golang
package main
import (
"context"
"fmt"
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/net/ghttp"
)
type HelloReq struct {
g.Meta `path:"/hello" method:"get" sm:"sm" dc:"dc"`
Name   string `v:"required" dc:"Your name"`
}
type HelloRes struct {
Reply string `dc:"Reply content"`
}
type Hello struct{}
func (Hello) Say(ctx context.Context, req *HelloReq) (res *HelloRes, err error) {
g.Log().Debugf(ctx, `receive say: %+v`, req)
res = &HelloRes{
Reply: fmt.Sprintf(`Hi %s`, req.Name),
}
return
}
func main() {
s := g.Server()
s.Use(ghttp.MiddlewareHandlerResponse)
s.Group("/", …
```
=> fix: disable map tag `summary` and `description` from the OpenAPI `Operation` to `PathItem`

net/ghttp/ghttp_server_log.go
param with chinese char format error
=> fix(ghttp): fix access log info format

util/gconv/gconv_map.go, util/gconv/gconv_struct.go, util/gconv/gconv_z_unit_map_test.go, util/gconv/gconv_z_unit_struct_test.go
Fix empty map or struct convert to another map will return error.
After fixed, it will return an empty map, not a nil or error.
=> Fix empty map or struct convert to another map will return error.

database/gdb/gdb_model_join.go
fix code comment err in Model Join case
=> docs: fix code comment err in Model Join case

internal/utils/utils_is.go, internal/utils/utils_z_unit_is_test.go
fix: https://github.com/gogf/gf/issues/2855
In the code of `gutil.IsSlice`, only `reflectValue` has changed during the loop, and `reflectKind` has not changed
=> fix: `gutil.IsSlice` judgment logic error

util/gconv/gconv_convert.go, util/gconv/gconv_z_unit_converter_test.go
fix: https://github.com/gogf/gf/issues/2665
Since v is of `interface{}` type, when v is assigned a value, the type of v is `interface{}|time.Time`, the function return type is interface{}, and the value type at this time is `interface{}|*interface{}|time .Time`, this will result in the original type `time.Time` not being available outside.
=> fix: multiple interfaces cause the original type to be inaccessible

encoding/gjson/gjson_z_unit_test.go, util/gconv/gconv_map.go
fix: https://github.com/gogf/gf/issues/2520
=> fix: gjson encode to string expect inconformity(issue 2520)

contrib/nosql/redis/redis.go, database/gredis/gredis_config.go
1. tls及tlsSkipVerify配置不生效
2. 在使用aws这类单endpoint的集群时，会错误地判定为单节点服务。故添加cluster配置项用于强行指定为集群服务。
=> add cluster mode and tls configuration support for package gredis

util/gconv/gconv_z_unit_time_test.go
pr https://github.com/gogf/gf/pull/2915 also fixes the problems mentioned in issue https://github.com/gogf/gf/issues/2901. This submission adds unit tests for issue https://github.com/gogf/gf/issues/2901.
=> test: add unit tests regarding issue 2901

net/ghttp/ghttp_middleware_tracing.go, os/gctx/gctx.go
1、项目底层上流调用链上报了WithCtx，此处干扰视线，影响界面显示，没法正常直观得看到展示的调用层
2、调用链上报的operation 是url, 这样会导致openration遍地繁衍，杂乱无章，如果想看具体请求业务日志，应当去日志系统查看
=> improve trace span generating for package gctx and http tracing content for package ghttp

util/gutil/gutil_list.go, util/gutil/gutil_z_unit_list_test.go
在数据表定义时，我使用了 binary(32) 作为其主键，并使用 gf 生成了对应的 do 与 entity, 其主键类型为 []byte 。在数据关联查询过程中使用了 ListItemValuesUnique 导致了 panic。
Debug 发现当去重的 map 指定的 key 为 []byte 时，go 会认为其 not comparable 直接 panic，<del> 考虑到 []byte 与 string 强转的内存拷贝问题，这里使用了 unsafe 来转换 StringHeader 与 SliceHeader 并将结果的 string 作为 key 进行去重操作 </del> 这里将 []byte 强转为 comparable 的 string 来进行 set key 操作
```
func Test_ListItemValuesUnique_Binary_ID(t *testing.T) {
gtest.C(t, func(t *gtest.T) {
listMap := g.List{
g.Map{"id": []byte{1}, "score": 100},
g.Map{"id": []byte{2}, "score": 100},
g.Map{"id": []byte{3}, "score": 100},
g.Map{"id": []byte{4}, "score": 100},
g.Map{"id": []byte{4}, "score": 100},
}
t.Assert(gutil.ListItemValuesUnique(listMap, "id"), g.Slice{[]byte{1}, []byte{2}, []byte{3}, []byte{4}}) …
```
=> fix(gutil): panic when field is []byte(BINARY in mysql)

os/glog/glog_logger.go
use printToStdout ,printToFile and  printToWriter at the same time
=> allowing use printToStdout, printToFile and printToWriter at the same time for Logger of package glog

net/ghttp/ghttp_middleware_tracing.go, net/ghttp/ghttp_z_unit_feature_middleware_basic_test.go
resolve response is gzip in internalMiddlewareServerTracing
the issue is:  #2792
=> resolve response is gzip in internalMiddlewareServerTracing

os/gcache/gcache_adapter_redis.go
修改 gcache_adapter_redis ，将秒级过期时间更新为毫秒级，使redis缓存与内存缓存表现一致，提高gcache可用性。修复秒级过期时间控制可能产生的精度逻辑问题。#3049
=> improve cache duration from second to millisecond for redis adapter of package gcache

contrib/nosql/redis/redis.go, database/gredis/gredis_config.go
The go-redis v9 has added support for RESP3 and communicates with the redis server using RESP3 by default. However, many cloud server manufacturers’ redis cloud services do not yet support RESP3. Therefore, when using the v9 client to connect to a redis server that does not support RESP3, some redis commands may fail to process the return value from the server, such as ‘zset range’. In order to be compatible with the RESP2 protocol, it is necessary to add configuration for the RESP version.
=> Add the Protocol attribute to the Redis configuration

cmd/gf/internal/utility/utils/utils.go
In windows if you configure type: "decimal.Decimal", then execute "gf gen dao" will report "go.mod not found in current project". After some troubleshooting, I found that utils.GetModPath() returns an empty string.
=> fix: "gf gen dao" utils.GetModPath Return empty string in windows

contrib/drivers/mssql/mssql_z_model_test.go, database/gdb/gdb_model_select.go
AllAndCount and ScanAndCount throw errors in SQL Server environment when there is an orderby statement。
sql server 2022 statement：
drop table if exists demo
create table demo(recid int identity(1,1),txt varchar(100),primary key(recid))
insert into demo(txt)values('txt1'),('txt2'),('txt3')
select * from demo
example code：
import (
"fmt"
_ "github.com/gogf/gf/contrib/drivers/mssql/v2"
"github.com/gogf/gf/v2/database/gdb"
)
func main() {
db, err := gdb.New(gdb.ConfigNode{
Link: `mssql:sa:123456@tcp(192.168.1.200:1433)/demo`,
})
if err != nil {
panic(err)
}
count, i, err := db.Model("demo").Order("recid").Limit(0, 10).AllAndCount(false)
if err != nil {
fmt.Println(err)
return
}
fmt.Println(count, i)
}
Error message：
SELECT COUNT(1) FROM demo ORDER BY recid: mssql: Column "demo.recid" is …
=> Fix the bug that ScanAndCount and AllAndCount report errors in sqlserver

example/httpserver/upload_file/main.go, net/ghttp/ghttp_request_param.go, net/ghttp/ghttp_z_unit_feature_config_test.go
fix #2938
如果需要body支持复读，可以在前置中间件中使用`r.MakeBodyRepeatableRead(true)`
```go
s.Group("/", func(group *ghttp.RouterGroup) {
group.Middleware(func(r *ghttp.Request) {
fmt.Println("middleware")
r.MakeBodyRepeatableRead(true)
r.Middleware.Next()
})
group.Middleware(ghttp.MiddlewareHandlerResponse)
group.Bind(cUpload{})
})
```
=> fix: #2938

contrib/drivers/dm/dm.go, contrib/drivers/dm/dm_init_test.go, contrib/drivers/dm/dm_z_basic_test.go, contrib/drivers/dm/go.mod, contrib/drivers/dm/go.sum
1. fix index character usage
2.  support DW mode
=> fix issues for package contrib/drivers/dm 

os/gstructs/gstructs_field.go, util/gutil/gutil_struct.go, util/gutil/gutil_z_unit_struct_test.go
=> enhance #3221

os/gcache/gcache_adapter_memory.go, os/gcache/gcache_cache.go
```go
package main
import (
"context"
"runtime"
"time"
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gcache"
)
func main() {
ctx := context.Background()
cache := gcache.NewAdapterMemory(1)
cache.Set(ctx, "key", "value", 10*time.Minute)
var m runtime.MemStats
timer1 := time.NewTicker(time.Microsecond)
timer2 := time.NewTicker(time.Second)
var i int
for {
select {
case <-timer1.C:
i++
cache.Get(ctx, "key")
case <-timer2.C:
runtime.ReadMemStats(&m)
size, _ := cache.Size(ctx)
g.Log().Infof(ctx, "memory usage: %dKB, gc num: %d, gcache size: %d, call times: %d", m.HeapInuse/1024, m.NumGC, size, i)
}
}
}                                                                                                                                               
```
=> fix: memory leak when gcache.NewAdapterMemory with lru

os/gcmd/gcmd_command_run.go, os/gcmd/gcmd_z_unit_feature_object1_test.go
=> feat: support running commands via non-command line arguments

contrib/drivers/mysql/mysql_z_unit_model_test.go
- Test_Model_OnDuplicate
- Test_Model_OnDuplicateEx
增加此两种方法的另外一种 string 类型：`OnDuplicate("passport", "password")`，以完善单测
=> enhance mysql_z_unit_model_test

net/ghttp/ghttp_middleware_tracing.go
gf opel auto report when body more than tracingMaxContentLogSize fail:
grpc:
traces export: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
http:
traces export: string field contains invalid UTF-8
=> fix: otel tracing content contains invalid UTF-8

contrib/drivers/mssql/mssql_z_unit_model_test.go, contrib/drivers/pgsql/pgsql_z_unit_model_test.go, contrib/drivers/pgsql/pgsql_z_unit_test.go, contrib/drivers/sqlite/sqlite_z_unit_model_test.go, contrib/drivers/sqlitecgo/sqlitecgo_z_unit_model_test.go, i18n/gi18n/gi18n_z_unit_test.go, net/gtcp/gtcp_z_unit_conn_pkg_test.go, os/gcfg/gcfg_z_unit_adapter_file_test.go, os/gtime/gtime_z_unit_test.go
`t.AssertNil(nil)` 居然没发现这么个低级错误 😢
=> fix: unit test error in PgSQL and SQLite; Unified `t.Assert(err, nil)` to `t.AssertNil(err)`

contrib/drivers/dm/dm_do_insert.go, contrib/drivers/dm/dm_z_unit_basic_test.go
**Dear reviewer:**
优化了 `dm` 数据库的 `save` 方法，换成了和 `Oracle` 一套的逻辑。
=> enhance: `Save` operation support for `contrib/drivers/dm`

net/ghttp/ghttp_response.go
Fix #3432 Add Access-Control-Expose-Headers: Content-Disposition header in ServeFileDownload
=> fix: #3432 Add Access-Control-Expose-Headers: Content-Disposition header in ServeFileDownload

contrib/trace/otlpgrpc/otlpgrpc.go, contrib/trace/otlphttp/otlphttp.go, example/trace/inprocess-grpc/main.go
**Dear review:**
在程序结束时要留有时间等待数据上报，不然有时候 otel 服务端会收不到，自建 `jaeger` 和阿里云都有这个问题。官网的示例也要改一下，不然新手会很疑惑。
=> fix: lost trace content in occasion when shutting down trace 

contrib/registry/etcd/etcd.go, contrib/registry/etcd/etcd_z_test.go
support etcd address use "ip:port,ip:port...,ip:port@username:password" to  etcd service which auth enabled
=> feat: add auth support in address configuration for etcd registry

database/gdb/gdb_model_soft_time.go
fix: The getSoftFieldName cache key name uses a random special certificate of the memory address causing infinite writing to the cache.
=> fix: invalid cache key using pointer address of variable for soft time fields

util/gconv/gconv_map.go
=> enhance: use map iter to iterate the map instead of map keys and values

os/gfsnotify/gfsnotify_watcher.go, os/gfsnotify/gfsnotify_watcher_loop.go, os/gfsnotify/gfsnotify_z_unit_test.go
fix: https://github.com/gogf/gf/issues/3396
=> fix: fsnotify watcher panics when closing

net/ghttp/ghttp_z_unit_feature_router_strict_test.go, util/gconv/gconv_slice_str.go, util/gconv/gconv_z_unit_slice_test.go
修复以下问题:</br>
1.当字符串的值为null时，调用gconv.Strings("null") 会返回nil
=> fix: #3465 If the value of a string is null, the value of string is nil after the string is converted to []string

contrib/registry/polaris/polaris_z_test.go, net/gclient/gclient_z_example_test.go, os/glog/glog_logger.go
=> chore: fix function names in comment

database/gdb/gdb_model_soft_time.go
当数据库（mysql）表结构定义类似：
```
CREATE TABLE `example`
(
`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
`created_at`  bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'created timestamp',
`updated_at` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'latest updated timestamp',
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
gf框架会将created_at与updated_at识别为soft-time可自动填充的字段，同时字段类型会被识别为：LocalTypeUint64。
但是在insert和update操作自动填充字段值的时候，不支持 LocalTypeUint64 类型的自动填充。
本PR补全了 LocalTypeUint64 类型的默认值填充逻辑。
=> database/gdb/gdb_model_soft_time: fix soft-time support fieldType:`LocalTypeUint64` in Insert/Update perations

cmd/gf/internal/cmd/cmd_z_unit_gen_dao_test.go, cmd/gf/internal/cmd/gendao/gendao_structure.go, os/gfile/gfile_replace.go
🐛 fix FieldMapping tablename match
🐛 fix ReplaceFileFunc content check
长度相同并不代表内容相同
=> cmd/gf: fix command `gf gen dao` for fieldMapping feature

cmd/gf/internal/cmd/cmd_z_unit_gen_pbentity_test.go, cmd/gf/internal/cmd/genpbentity/genpbentity.go, cmd/gf/internal/cmd/testdata/issue/3545/table_user.proto
=> cmd/gf: fix pbentity generate fail in mono-repo

cmd/gf/internal/consts/consts_gen_ctrl_template_sdk.go, contrib/sdk/httpclient/handler.go, contrib/sdk/httpclient/httpclient.go, contrib/sdk/httpclient/httpclient_config.go, contrib/sdk/httpclient/httpclient_handler.go, contrib/sdk/httpclient/httpclient_z_unit_feature_handler_test.go
=> contrib/sdk/httpclient: add custom response handler support, fixe #3539

cmd/gf/internal/cmd/cmd_build.go, contrib/drivers/pgsql/pgsql_tables.go
**Please ensure you adhere to every item in this list.**
every time function **Index** and **version** execute, these regexp are initialized. which situation reduce the performance.
=> driver/pgsql: optimize regex for version matching

contrib/registry/zookeeper/zookeeper_discovery.go, contrib/registry/zookeeper/zookeeper_registrar.go
服务注册的时候zookeeper_registrar里会取service.GetPrefix()得到的prefix是service-default-default-idalloc-latest，而在查找服务时
resolver_builder里用target.URL.Path作为watchKey，是这样的/service/default/default/idalloc/latest/，传到zookeeper_discovery的Search里 prefix转成了service-default-default-idalloc-latest-，最后面有个杠-
=> contrib/registry/zookeeper: fix invalid searching prefix

cmd/gf/go.mod, cmd/gf/go.work, cmd/gf/internal/cmd/cmd_gen_dao.go, cmd/gf/internal/cmd/gendao/gendao_dao.go, cmd/gf/internal/cmd/gendao/gendao_do.go, cmd/gf/internal/cmd/gendao/gendao_entity.go, cmd/gf/internal/cmd/gendao/gendao_structure.go
The purpose is to be able to use the DM database to build a CLI.
=> cmd/gf: add `DaMeng` database driver support

os/gres/gres_func_zip.go, os/gres/gres_z_unit_test.go
=> os/gres: fix #3611 add custom prefix `/` support for resource packing

contrib/drivers/pgsql/pgsql_do_exec.go
**When the field name in pgsql is uppercase, the field must be enclosed in quotation marks; otherwise, an error will occur indicating that the field cannot be found. Therefore, a modification was made to change it to RETURNING "ID" in this style.**
-------------------------------------------
当pgsql的字段名大写时，必须把字段用"给引用起来，否则会报错，提示找不到字段，所以作出修改，改成了 RETURNING "ID"，这种样式。
=> drivers/pgsql:pgsql returning id should use quotation marks,when primary key is capital

cmd/gf/internal/cmd/cmd_run.go
**Dear reviewer:**
在 `gf run` 结束时删除临时使用的二进制文件，另外，统一了不同系统的分隔符
=> cmd/gf: delete binary file when gf run end process

contrib/drivers/pgsql/pgsql_convert.go, contrib/drivers/pgsql/pgsql_z_unit_issue_test.go, contrib/drivers/pgsql/testdata/issues/issue3632.sql
=> contrib/drivers/pgsql: support slice type to insert into array for pgsql

database/gdb/gdb_core_trace.go, go.mod
#3658 
改为统一的官方协议，以及去除重复记录，减少trace的存储大小
=> database/gdb: remove duplicated SQL records in tracing events

cmd/gf/internal/cmd/cmd_up.go
`gf up`命令会在`go get`的时候加上`-u`参数，这会导致强制升级某些间接依赖，会导致依赖的go版本大于当前环境版本而导致报错。
如下图所示，带了`-u`参数会报错，只使用`@latest`标签则正常
=> fix(cmd/gf): fix command `gf up` with `-u` option upgrading packages indirectly required would fail with higher version of go required

contrib/config/kubecm/go.mod, contrib/config/kubecm/go.sum, contrib/config/nacos/go.mod, contrib/config/nacos/go.sum, contrib/config/polaris/go.mod, contrib/config/polaris/go.sum, contrib/metric/otelmetric/go.mod, contrib/metric/otelmetric/go.sum, contrib/registry/etcd/go.mod, contrib/registry/etcd/go.sum, contrib/registry/nacos/go.mod, contrib/registry/nacos/go.sum, contrib/registry/polaris/go.mod, contrib/registry/polaris/go.sum, contrib/rpc/grpcx/go.mod, contrib/rpc/grpcx/go.sum, contrib/trace/otlpgrpc/go.mod, contrib/trace/otlpgrpc/go.sum, contrib/trace/otlphttp/go.mod, contrib/trace/otlphttp/go.sum, example/go.mod, example/go.sum
=> build: bump google.golang.org/protobuf to v1.33.0

contrib/nosql/redis/redis_group_script.go
=> fix(contrib/nosql/redis): missing err nil check in function `ScriptExists`

contrib/drivers/mysql/mysql_z_unit_issue_test.go, os/gtime/gtime_sql.go, os/gtime/gtime_z_example_time_test.go
```go
// Value is the interface providing the Value method for package database/sql/driver
// for retrieving value from golang variable to database.
func (t *Time) Value() (driver.Value, error) {
if t == nil {
return nil, nil
}
if t.IsZero() {
return nil, nil
}
if t.Year() == 0 {
// Only time.
return t.Format("15:04:05"), nil
}
return t.Time, nil
}
```
the pr can Fixes #2012
=> fix(os/gtime): fix gtime.Value() when time only, add `time only` example

contrib/drivers/mysql/mysql_z_unit_issue_test.go, database/gdb/gdb_func.go
fix #3649 when constructing query param, `gdb.Row` value not directly write to Buffer
=> fix(database/gdb): fix #3649 when constructing query param, `gdb.Row` value not directly write to Buffer

contrib/drivers/pgsql/pgsql_convert.go, contrib/drivers/pgsql/pgsql_z_unit_issue_test.go, contrib/drivers/pgsql/testdata/issues/issue3671.sql
**Please ensure you adhere to every item in this list.**
+ The PR title is formatted as follows: `<type>[optional scope]: <description>` For example, `fix(os/gtime): fix time zone issue`
+ `<type>` is mandatory and can be one of `fix`, `feat`, `build`, `ci`, `docs`, `style`, `refactor`, `perf`, `test`, `chore`
+ fix: Used when a bug has been fixed.
+ feat: Used when a new feature has been added.
+ build: Used for modifications to the project build system, such as changes to dependencies, external interfaces, or upgrading Node version.
+ ci: Used for modifications to continuous integration processes, such as changes to Travis, Jenkins workflow configurations.
+ docs: Used for modifications to documentation, such as changes to README files, API documentation, etc.
+ style: Used for changes …
=> fix(contrib/drivers/pgsql): #3671 fix invalid pgsql insert json type

util/gconv/gconv_convert.go, util/gconv/gconv_z_unit_issue_test.go
Fixes https://github.com/gogf/gf/issues/3731
=> fix(util/gconv): #3731 map type name mismatch in switch case statement

net/goai/goai_requestbody.go, net/goai/goai_z_unit_test.go
Fixes #3605
---
When I was debugging, I found that tags such as `v: "min"`,`v: "max"` were not rendered in the `openapi.json`
Is this as expected?
- Request & Response
```go
type CreateReq struct {
g.Meta `path:"/Schema" tags:"schema" method:"POST" summary:"Create"`
Option   string `dc:"option field"`
Required string `v:"required" dc:"required field"`
Min      int    `v:"min:1" d:"100" dc:"minimum value"`
Max      int    `v:"max:10" d:"-1" dc:"maximum value"`
}
type CreateRes struct {
Option   string `dc:"option field"`
Required string `v:"required" dc:"required field"`
Min      int    `v:"min:1" d:"200" dc:"minimum value"`
Max      int    `v:"max:10" d:"-2" dc:"maximum value"`
}
```
- Swagger UI
<details>
<summary>Demo Code</summary>
```go
package main
import (
"context" …
```
=> fix(net/goai): fix openapi miss `required` tag of `BizRequest` when set `CommonRequest`

contrib/drivers/mysql/mysql_z_unit_issue_test.go, contrib/drivers/mysql/testdata/issue3754.sql, database/gdb/gdb_model.go, database/gdb/gdb_model_fields.go, database/gdb/gdb_model_insert.go, database/gdb/gdb_model_select.go, database/gdb/gdb_model_update.go, database/gdb/gdb_model_utility.go
=> fix(database/gdb): #3754 FieldsEx feature conflicts with soft time feature in soft time fields updating

debug/gdebug/gdebug_caller.go, debug/gdebug/gdebug_z_unit_internal_test.go, debug/gdebug/gdebug_z_unit_test.go
=> fix(debug/gdebug): incorrect package name handling in function CallerPackage

errors/gcode/gcode.go, os/gcache/gcache_adapter_memory.go, os/gcache/gcache_adapter_memory_expire_sets.go
=> fix(os/gcache): a little memory leak for removed timestamp key

container/glist/glist_z_unit_test.go, internal/deepcopy/deepcopy_test.go, net/ghttp/ghttp_server_config_api.go, net/ghttp/ghttp_z_unit_issue_test.go, net/goai/goai_path.go, net/goai/goai_z_unit_issue_test.go, os/glog/glog_logger.go, os/glog/glog_logger_api.go, util/gconv/gconv_z_unit_issue_test.go, util/gtag/gtag.go
=> fix(net/goai): change default value of RequestBody.Required from true to false, add required tag support for RequestBody

contrib/drivers/oracle/oracle_order.go, contrib/drivers/oracle/oracle_z_unit_model_test.go, contrib/drivers/pgsql/pgsql_order.go, contrib/drivers/pgsql/pgsql_z_unit_model_test.go, contrib/drivers/sqlite/sqlite_order.go, contrib/drivers/sqlite/sqlite_z_unit_model_test.go, database/gdb/gdb.go, database/gdb/gdb_core_underlying.go, database/gdb/gdb_model_order_group.go
Dear review：
不同数据库 `order by rand()` 子句中使用的函数是不一样的，orm 之前固定使用 `rand()` 函数，无法支持 **oracle, pg, sqlite**
fixed #3705
=> fix(database/gdb): support OrderRandom feature in different databases

contrib/registry/etcd/etcd.go
add DialTimeout parameter to prevent the service from blocking the program when it is not started
add AutoSyncInterval  fix https://github.com/gogf/gf/issues/3683
=> feat(contrib/registry/etcd/): add `DialTimeout` and `AutoSyncInterval` option

contrib/rpc/grpcx/internal/tracing/tracing.go, contrib/rpc/grpcx/internal/tracing/tracing_interceptor_client.go, contrib/rpc/grpcx/internal/tracing/tracing_interceptor_server.go, net/gclient/gclient_observability.go, net/gclient/gclient_tracer_tracing.go, net/ghttp/ghttp_middleware_tracing.go
fixed #3791 
It is necessary adding request and response content to opentelemetry tracing attributes, which will slow the performance for http & grpc operations.
The main purpose of tracing is to locate the error among services.
=> fix(net/ghttp&gclient,contrib/rpc/grpcx): remove request and response contents in opentelemetry tracing attributes

os/gcache/gcache.go, os/gcache/gcache_adapter_memory.go, os/gcache/gcache_adapter_memory_data.go, os/gcache/gcache_adapter_memory_expire_sets.go, os/gcache/gcache_adapter_memory_expire_times.go, os/gcache/gcache_adapter_memory_item.go, os/gcache/gcache_adapter_memory_lru.go, os/gcache/gcache_adapter_redis.go, os/gcache/gcache_cache.go, os/gcache/gcache_z_bench_test.go, os/gcache/gcache_z_example_cache_test.go, os/gcache/gcache_z_unit_test.go
=> fix(os/gcache): memory leak for LRU when adding operations more faster than deleting

.github/workflows/ci-main.yml
refer https://github.com/actions/runner-images/issues/10649
=> ci: fix mssql docker service starting failed

cmd/gf/internal/cmd/cmd_z_unit_gen_service_test.go, cmd/gf/internal/cmd/genservice/genservice_ast_parse.go, cmd/gf/internal/cmd/testdata/issue/3835/logic/issue3835/issue3835.go, cmd/gf/internal/cmd/testdata/issue/3835/logic/logic.go, cmd/gf/internal/cmd/testdata/issue/3835/service/issue_3835.go
Dear review:
当 logic 中存在类似携带版本号的引入包名，例如：`github.com/gogf/gf/v2`，那么在生成 `service` 的时候，会导致该包名识别为 `v2`。
故此当结尾以版本号结尾时，向前推进一位，使用正确的 `gf` 做为包名。
Fixed #3835
=> fix(cmd/gf): gen service error when there's version number at the end of package import path

util/gconv/gconv_struct.go, util/gconv/gconv_z_unit_issue_test.go
删除bindStructWithLoopParamsMap函数根据fuzzLastKey查找的逻辑
fix #3868
=> fix(util/gconv): incorrect fuzzy converting logic

contrib/drivers/clickhouse/clickhouse_z_unit_model_test.go, contrib/drivers/mssql/mssql_z_unit_model_test.go, contrib/drivers/mysql/mysql_z_unit_model_test.go, contrib/drivers/oracle/oracle_z_unit_model_test.go, contrib/drivers/pgsql/pgsql_z_unit_model_test.go, contrib/drivers/sqlite/sqlite_z_unit_model_test.go, contrib/drivers/sqlitecgo/sqlitecgo_z_unit_model_test.go, database/gdb/gdb_model_select.go
database/gdb: add exist feature  #3657 reopen
=> feat(database/gdb): add Exist support for checking records existance for certain condition

util/gconv/gconv_struct.go, util/gconv/gconv_z_unit_issue_test.go, util/gconv/internal/structcache/structcache_cached_struct_info.go
删除bindStructWithLoopParamsMap的逻辑,
只保留一个赋值的逻辑，当时使用bindStructWithLoopParamsMap
是因为paramsMap的长度可能比被赋值的结构体字段数多，
所以会以paramsMap的长度来做主循环，以减少循环次数，达到性能提升的目的
且维护两个逻辑，可能会对测试的结果有影响，
我在bindStructWithLoopParamsMap的逻辑后，有一个测试就没通过
在bindStructWithLoopFieldInfos的逻辑没办法通过记录赋值次数来判断可以提前退出，
```go
type Data struct {
A int `json:"a" orm:"a" conv:"a" p:"a"`
B int `json:"b" orm:"a" conv:"a" p:"a"`
C int `json:"c"`
}
paramsMap := map[string]any{
"c": 3,
}
// 此时有3个字段
// 根据A,B,C的顺序来循环查找paramsMap
// 这时候要循环到第三次才能找到paramsMap.c并给C字段赋值
// 在前两次没有找到的时候，也需要使用A和B字段的tag来循环依次查找paramsMap
// 相当于查找8+1次
// 在原版的bindStructWithLoopParamsMap逻辑下可能只需要1次
// 当然这是最极端的情况
// 更多的可能是下面这种情况
paramsMap2 := map[string]any{
"a": 2,
"c": 3,
}
```
=> fix(util/gconv): assigned the same value to struct field and its same name field in embedded struct failed

cmd/gf/internal/cmd/genpb/genpb.go
Dear review:
在 `gen pb` 中会使用 `gfile.Chdir` 改变当前工作路径，而 `gen pbentity` 则依赖当前工作路径生成 `go_package in *.proto`。如此一来，一旦两者同时进行单测，`gen pbentity` 生成的 `*.proto` 会出现意外的 `go_package`，导致单测失败。
详情查看：https://github.com/gogf/gf/actions/runs/11513842473/job/32051852646
fixed: #3894
=> fix(cmd/gf): go back current working directory after gf gen pb

database/gdb/gdb_model_order_group.go
remove Eg:Order(id,desc) from function Order comments, since new version no more support this mode. it will cause error. treat asc and desc as a column
=> chore(database/gdb): comment update for function `Model.Order`

os/gcache/gcache_adapter_memory.go
=> fix(os/gcache): function `Remove` returns value not `*gvar.Var` as previous version

cmd/gf/internal/cmd/cmd_build.go
调整打印环境变量的位置，修复cmd build命令打印env与实际不符的问题
=> fix(cmd/gf): incorrect environment variables printing before cli does some environment changes

cmd/gf/internal/cmd/cmd_z_unit_gen_pbentity_test.go, cmd/gf/internal/cmd/genpbentity/genpbentity.go, cmd/gf/internal/cmd/testdata/genpbentity/generated/table_user.proto, cmd/gf/internal/cmd/testdata/genpbentity/generated/table_user_snake_screaming.proto, cmd/gf/internal/cmd/testdata/issue/3685/table_user.proto, cmd/gf/internal/cmd/testdata/issue/3685/user.tpl.sql
- Introduced `typeMapping` to map database types to protobuf types.
- Added `fieldMapping` for customizable field name conversion.
fixes gogf/gf#3685
=> feat(cmd/gf): add `typeMapping` and `fieldMapping` feature support for command `gf gen genpbentity`

util/gvalid/gvalid_z_unit_feature_rule_test.go, util/gvalid/internal/builtin/builtin_enums.go
Fix the error when defining API parameter types using enum pointer
=> fix(utils/gvalid): missing pkg path for enums pointer

net/ghttp/ghttp_response_cors.go
https://github.com/gogf/gf/pull/3986#issuecomment-2507522224
> Example 2 has a problem.
>
> ```go
>referer := "https://example.com/path/to/page.html"
> if p := gstr.PosR(referer, "/", 6); p != -1 {
> 	fmt.Println(referer[:p]) //https://example.com/path/to
> } else {
> 	fmt.Println(referer)
> }
> ```
=> fix(net/ghttp): get origin through referer

net/gipv4/gipv4.go, net/gipv4/gipv4_convert.go, net/gipv4/gipv4_z_unit_convert_test.go
Dear Review:
增强 `ipv4` 地址的转换，包含大小端序
Closed: #3984
=> feat(net/gipv4): add enhanced the conversion between uint32 and string

database/gdb/gdb_model_soft_time.go, encoding/gjson/gjson_api_encoding.go, util/grand/grand_buffer.go
fix some function names in comment
=> chore: fix some function names in comment

.github/workflows/golangci-lint.yml, util/gpage/gpage.go
Fixes [https://github.com/gogf/gf/security/code-scanning/9](https://github.com/gogf/gf/security/code-scanning/9)
To fix the problem, we need to ensure that the `title` parameter is properly escaped before being embedded in the HTML attribute. The best way to fix this is to use a proper HTML escaping function that will convert special characters to their corresponding HTML entities. This will prevent any special characters in the `title` from breaking the HTML structure.
We will use the `html.EscapeString` function from the `html` package to escape the `title` parameter. This function converts special characters like `<`, `>`, `&`, and `"` to their corresponding HTML entities.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> fix(util/gpage): code scanning alert no. 9: Potentially unsafe quoting

util/gutil/gutil_dump.go
Fixes [https://github.com/gogf/gf/security/code-scanning/17](https://github.com/gogf/gf/security/code-scanning/17)
To fix the problem, we need to ensure that single quotes are also escaped in the `addSlashesForString` function. This will prevent any potential injection vulnerabilities when the resulting string is embedded in a context that uses single quotes for quoting.
- Modify the `addSlashesForString` function to escape single quotes.
- Ensure that the escaping mechanism is consistent with the context in which the string will be used.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> fix(util/gutil): code scanning alert no. 17: Potentially unsafe quoting

contrib/drivers/mysql/mysql_z_unit_issue_test.go, contrib/drivers/mysql/testdata/issue3915.sql, database/gdb/gdb_core.go, database/gdb/gdb_func.go, text/gstr/gstr_replace.go, text/gstr/gstr_z_example_test.go, text/gstr/gstr_z_unit_replace_test.go
fix https://github.com/gogf/gf/issues/3915
=> fix(database/gdb): move `Raw` parameter from args to sql statement before committed to db driver

cmd/gf/internal/cmd/cmd_z_unit_gen_pb_test.go, cmd/gf/internal/cmd/genpb/genpb_tag.go, cmd/gf/internal/cmd/testdata/issue/3953/issue3953.proto
=> fix(cmd/gf): custom tags repeatedly added using command `gf gen pb` with `-a` option

net/ghttp/ghttp_request_param_ctx.go, os/gctx/gctx.go, os/gctx/gctx_z_unit_test.go
- Removed the `gctx.WithCtx` function from ghttp.
- Renamed `gctx.WithCtx` to `gctx.WithSpan` to prevent naming ambiguity.
=> feat(gctx): rename and remove gctx functions to prevent ambiguity

example/httpserver/swagger/main.go, net/ghttp/ghttp_server_config_api.go, net/ghttp/ghttp_z_unit_feature_openapi_swagger_test.go
=> chore: add example for openapi/swagger authentication

contrib/drivers/mysql/mysql_z_unit_issue_test.go, contrib/drivers/mysql/testdata/issue2119.sql, database/gdb/gdb_model_with.go, os/gstructs/gstructs_z_unit_test.go
this PR is updated from https://github.com/gogf/gf/pull/3559
fix https://github.com/gogf/gf/issues/2119
=> fix(database/gdb): orm tag from embedded struct is missing in `with` feature

database/gdb/gdb.go
style: fix typos in comments (use CRUD instead of CURD)
based on https://en.wikipedia.org/wiki/Create,_read,_update_and_delete
=> fix(database/gdb): CRUD typos

LICENSE, contrib/drivers/clickhouse/clickhouse_open.go, contrib/drivers/clickhouse/clickhouse_z_unit_test.go, contrib/drivers/mssql/mssql_open.go, contrib/drivers/mysql/mysql_open.go, contrib/drivers/oracle/oracle_open.go, contrib/drivers/pgsql/pgsql_open.go, contrib/drivers/sqlite/sqlite_open.go, contrib/drivers/sqlite/sqlite_z_unit_core_test.go, contrib/drivers/sqlitecgo/sqlitecgo_open.go, contrib/drivers/sqlitecgo/sqlitecgo_z_unit_core_test.go, database/gdb/gdb.go, database/gdb/gdb_core_config.go, database/gdb/gdb_z_mysql_internal_test.go, frame/gins/gins_database.go
fix https://github.com/gogf/gf/issues/4018
=> fix(contrib/drivers/pgsql): add unix socket connection support

contrib/drivers/pgsql/pgsql_convert.go
enhance #4000，One line change, Return basic types instead of pq.StringArray to reduce one reflection assignment when calling gconv.Strings in doStruct, minimizing performance overhead.
=> perf(contrib/drivers/pgsql): improve conversion performace for slice string

database/gdb/gdb.go, database/gdb/gdb_z_mysql_internal_test.go
=> fix(database/gdb): regular expression pattern for link configuration to be compitable with tidbcloud

net/ghttp/ghttp_server_config.go, net/ghttp/ghttp_server_config_logging.go, net/ghttp/ghttp_server_log.go, net/ghttp/ghttp_z_unit_issue_test.go
fix https://github.com/gogf/gf/issues/4047
=> fix(net/ghttp): nil pointer panic error when server logger set nil

contrib/drivers/mysql/mysql_z_unit_model_test.go, contrib/drivers/pgsql/pgsql_format_upsert.go, contrib/drivers/pgsql/pgsql_z_unit_model_test.go, contrib/drivers/sqlite/sqlite_z_unit_model_test.go, contrib/drivers/sqlitecgo/sqlite_format_upsert.go, contrib/drivers/sqlitecgo/sqlitecgo_do_filter.go, contrib/drivers/sqlitecgo/sqlitecgo_tables.go, contrib/drivers/sqlitecgo/sqlitecgo_z_unit_init_test.go, contrib/drivers/sqlitecgo/sqlitecgo_z_unit_model_test.go, database/gdb/gdb_core.go, database/gdb/gdb_core_underlying.go
fix gdb.Counter not work in OnDuplicate
=> fix(database/gdb): `gdb.Counter` not work in `OnDuplicate`

os/gcmd/gcmd_command.go, os/gcmd/gcmd_command_help.go, os/gcmd/gcmd_command_object.go
the effect is similar to:
old: 
```
-p, --path       output binary directory path, default is './bin'
```
new:
```
-p, --path       output binary directory path, default is './bin' (default: "./bin")
```
=> feat(os/gcmd): add default value display for an argument

net/ghttp/ghttp_middleware_handler_response.go, net/ghttp/ghttp_z_unit_issue_test.go
fix https://github.com/gogf/gf/issues/4108
=> fix(net/ghttp): `MiddlewareHandlerResponse` writes additional information after custom response wrote

contrib/config/polaris/polaris.go
polaris conf update use gjson.LoadContent not gjson.DecodeToJson to support multiple format conf content.
Fixs #4104 4104
=> fix(contrib/config/polaris): it only supports json format for configuration contents, add more content formats support

test/gtest/gtest_util.go, test/gtest/gtest_z_unit_test.go
AssertNI/AssertIN func support map type
```go
func TestAssertIN_Map(t *testing.T) {
gtest.C(t, func(t *gtest.T) {
t.AssertIN("k1", map[string]string{"k1": "v1", "k2": "v2"})
t.AssertIN(1, map[int64]string{1: "v1", 2: "v2"})
t.AssertIN([]string{"k1", "k2"}, map[string]string{"k1": "v1", "k2": "v2"})
})
}
func TestAssertNI_Map(t *testing.T) {
gtest.C(t, func(t *gtest.T) {
t.AssertNI("k3", map[string]string{"k1": "v1", "k2": "v2"})
t.AssertNI(3, map[int64]string{1: "v1", 2: "v2"})
t.AssertNI([]string{"k3", "k4"}, map[string]string{"k1": "v1", "k2": "v2"})
})
}
```
=> feat(test/gtest): add map type support for `AssertNI/AssertIN`

net/ghttp/ghttp_request_param.go, net/ghttp/ghttp_z_unit_feature_request_struct_test.go
在 net/ghttp/ghttp_request_param.go 中 parseForm函数 在 MakeBodyRepeatableRead(true)执行之前解析表单，导致GetBody() 获取不到Body内容
=> fix(net/ghttp): `MakeBodyRepeatableRead` takes not effective when called after `ParseForm`

cmd/gf/internal/cmd/genpbentity/genpbentity.go
当自定义 pbentity 包名后，这个包名会同时应用于 proto 文件包名和 option go_package 名，这两个名字本身命令规范是不一样的，所以生成的文件存在问题。这里新增 goPackage 配置项来指定 go_package 名
=> feat(cmd/gf): add `gopackage` option for command `gf gen pbentity` to specify `go_package` for generated proto files

util/gconv/gconv_z_unit_scan_test.go, util/gvalid/internal/builtin/builtin_between.go, util/gvalid/internal/builtin/builtin_float.go, util/gvalid/internal/builtin/builtin_gt.go, util/gvalid/internal/builtin/builtin_gte.go, util/gvalid/internal/builtin/builtin_lt.go, util/gvalid/internal/builtin/builtin_lte.go, util/gvalid/internal/builtin/builtin_max.go, util/gvalid/internal/builtin/builtin_min.go
when I run `staticcheck ./...` in `util` dir it show warning message:
`
gvalid/internal/builtin/builtin_between.go:42:64: 'bitSize' argument is invalid, must be either 32 or 64 (SA1030)
`
=> chore(util/gvalid): using `64` instead of `10` bitsize parameter for function `strconv.ParseFloat` although it treats `10` as `64` internally

.github/workflows/golangci-lint.yml, cmd/gf/internal/cmd/genpbentity/genpbentity.go, contrib/config/polaris/polaris.go, net/ghttp/ghttp_middleware_handler_response.go, net/ghttp/ghttp_request_param.go, net/ghttp/ghttp_request_param_request.go, net/ghttp/ghttp_server_service_handler.go, net/ghttp/ghttp_z_unit_feature_openapi_swagger_test.go, net/ghttp/ghttp_z_unit_feature_request_struct_test.go, net/ghttp/ghttp_z_unit_feature_router_strict_test.go, net/ghttp/ghttp_z_unit_issue_test.go, os/gproc/gproc_z_unit_test.go, test/gtest/gtest_util.go, test/gtest/gtest_z_unit_test.go, util/gconv/gconv_z_unit_scan_test.go, util/gvalid/gvalid_z_unit_issue_test.go, util/gvalid/internal/builtin/builtin_between.go, util/gvalid/internal/builtin/builtin_float.go, util/gvalid/internal/builtin/builtin_gt.go, util/gvalid/internal/builtin/builtin_gte.go, util/gvalid/internal/builtin/builtin_lt.go, util/gvalid/internal/builtin/builtin_lte.go, util/gvalid/internal/builtin/builtin_max.go, util/gvalid/internal/builtin/builtin_min.go
修复没有读取code的message问题，参考https://github.com/gogf/gf/pull/4124
=> fix(net/ghttp): update response message handling in `MiddlewareHandlerResponse`

cmd/gf/main.go
fix bug: could not load time location: "unknown time zone Asia/Shanghai"
The bug will appear when I use gf in windows to do "gf gen dao" for clickhouse.
=> fix(cmd/gf): "unknown time zone" when using "gf gen dao" for clickhouse on windows platform

README.MD
Why is this needed:
The OpenSSF Scorecard improves open-source project's security by providing automated, transparent assessments of their security practices. It will help you identify vulnerabilities, adhere to best practices, and continuously enhance your security posture, increasing user trust and reducing the risk of security exploits.
I'll be the one to create the PR to add the scorecard GitHub action, and I will also work with you to remediate the identified vulnerabilities. I'll go through each [scorecard check](https://github.com/ossf/scorecard/blob/main/docs/checks.md) to see where the score has dropped and how it can be improved.
Integrate [scorecard](https://github.com/ossf/scorecard) in CI, and display a Scorecard badge on the gogf repository
You also need to manually create a …
=> chore: add OpenSSF Scorecard for README.md

net/goai/goai_path.go, net/goai/goai_z_unit_issue_test.go
fix https://github.com/gogf/gf/issues/4247
=> fix(net/goai): fix g.Meta is passed as parameters of a request

.github/workflows/tag.yml
Update dependencies and ensure that go.mod files in the test data directory are excluded from processing during the tag creation for the CLI tool.
=> fix: Update dependencies and exclude test data from go.mod processing

database/gdb/gdb_model_hook.go
error log
```
2025-06-18T15:36:08.315+08:00 [DEBU] {10a3b0cfd9124a186b89b07f50e67ce6} [  0 ms] [default] [db_0] [rows:1  ] SELECT `id`,`custom_name` FROM `custom` WHERE `id`=1 LIMIT 1
2025-06-18T15:36:09.259+08:00 [DEBU] {10a3b0cfd9124a186b89b07f50e67ce6} [  1 ms] [default] [db_0] [rows:1  ] SELECT `id`,`custom_name`,`remark`FROM `custom` WHERE `id`=2 LIMIT 1
```
right log
```
2025-06-18T15:36:08.315+08:00 [DEBU] {10a3b0cfd9124a186b89b07f50e67ce6} [  0 ms] [default] [db_0] [rows:1  ] SELECT `id`,`custom_name` FROM `custom` WHERE `id`=1 LIMIT 1
2025-06-18T15:36:09.259+08:00 [DEBU] {10a3b0cfd9124a186b89b07f50e67ce6} [  1 ms] [default] [db_1] [rows:1  ] SELECT `id`,`custom_name`,`remark`FROM `custom` WHERE `id`=2 LIMIT 1
```
```
type DbShardingRule struct {
}
func (d *DbShardingRule) …
```
=> fix(database/gdb):  Resolved the schema error in the database output log when using the database sharding feature

contrib/drivers/mysql/mysql_z_unit_issue_test.go
Resolve a temporary issue in the unit tests for batch insertion by adjusting user IDs.
因为底层的插入随机性，会导致单元测试偶发失败。
=> fix(contrib/drivers/mysql): Fix unit test issue for batch insert in MySQL driver
