gogf/gf

geg/other/test.go
您好，这是我的第一次代码贡献，希望能够合并进您的master分支！
=> test merge

g/os/gtime/gtime.go, g/os/gtime/gtime_z_bench_test.go, g/os/gtime/gtime_z_unit_basic_test.go, g/os/gtime/gtime_z_unit_format_test.go, g/os/gtime/gtime_z_unit_time_test.go
=>  Add gtime unit test

g/encoding/ghash/ghash_z_unit_basic_test.go
add ghash basic test
19/06/12 11:40
=> add ghash basic test

g/container/garray/garray_sorted_int.go
=> add glist unit tests

g/crypto/gaes/gaes.go, g/crypto/gaes/gaes_test.go
=> gaes encryption and decryption add CFB mode

g/util/gutil/gutil_comparator_z_unit_test.go, g/util/gutil/gutil_z_unit_test.go
已修改 gutil test 2019 06 25 15:52
=> gutil test

g/os/gfile/gfile.go, g/os/gfile/gfile_z_test.go, go.mod
=> Feature filecopy

.travis.yml, database/gdb/gdb_mssql.go, database/gdb/gdb_oracle.go, database/gdb/gdb_pgsql.go, database/gdb/gdb_structure.go, database/gdb/gdb_unit_0_init_test.go, database/gdb/gdb_unit_init_mssql_test.go, database/gdb/gdb_unit_init_oracle_test.go, database/gdb/gdb_unit_init_pgsql_test.go, database/gdb/gdb_unit_init_test.go, database/gdb/gdb_unit_z_method_test.go, database/gdb/gdb_unit_z_model_test.go, database/gdb/gdb_unit_z_mssql_method_test.go, database/gdb/gdb_unit_z_mssql_model_test.go, database/gdb/gdb_unit_z_mssql_struct_test.go, database/gdb/gdb_unit_z_mssql_transaction_test.go, database/gdb/gdb_unit_z_oracle_method_test.go, database/gdb/gdb_unit_z_oracle_model_test.go, database/gdb/gdb_unit_z_oracle_struct_test.go, database/gdb/gdb_unit_z_oracle_transaction_test.go, database/gdb/gdb_unit_z_pgsql_method_test.go, database/gdb/gdb_unit_z_pgsql_model_test.go, database/gdb/gdb_unit_z_transaction_test.go, encoding/gini/gini.go, encoding/gini/gini_test.go, encoding/gjson/gjson_api_encoding.go, encoding/gjson/gjson_api_new_load.go, encoding/gjson/gjson_z_unit_load_test.go, encoding/gparser/gparser_api_encoding.go, encoding/gparser/gparser_api_new_load.go
=> 增加gdb的测试案例，增加gini包

.example/net/gsmtp/gsmtp_sendMail.go, net/gsmtp/gsmtp.go
server address verification
simple Email address check for from & to
default port=25 for server address
=> Slightly improved usability

util/grand/grand.go
The 'letters' already contain numbers, so just grab characters randomly from this.
=> 优化函数grand.Str

database/gdb/gdb_base.go
=> fix mysql debug time

net/ghttp/ghttp_server_router_group.go
=> 分组路由对象绑定时支持多方法绑定

DONATOR.MD, README_ZH.MD
=> 更新 readme 中文版

database/gdb/gdb_driver_mssql.go
仿照mysql的方式，增加 Null,Key,Default,Extra,Comment
=> improve mssql TableFields func

os/glog/glog_logger.go
#741 
```
glog.SetFlags(glog.GetFlags() | glog.F_CALLER_FN)
glog.Info("Test")
// 2020-06-22 11:08:47.041 [INFO] [main.main] Test
```
=> log added function name display

README.MD, README_ZH.MD
=> update tencent site

database/gdb/gdb_driver_pgsql.go, database/gdb/gdb_func.go
postgre 报错 pq: syntax error at or near $
=> postgre 报错 pq: syntax error at or near $

database/gredis/gredis.go, database/gredis/gredis_config.go, database/gredis/gredis_z_unit_test.go
=> support redis tls

os/gcache/gcache.go, os/gcache/gcache_mem_cache.go, os/gcache/gcache_z_unit_1_test.go
add func gcache.SetVar/gcache.SetExpire/gcacge.GetExpire.
add test TestCache_Expire_SetVar.
=> add func gcache.SetVar/gcache.SetExpire/gcacge.GetExpire.

database/gdb/gdb.go, database/gdb/gdb_core.go, database/gdb/gdb_func.go, database/gdb/gdb_z_mysql_method_test.go
add update counter method for package gdb.
=> add update counter method for package gdb.

database/gdb/gdb_model_insert.go
=> fix InsertIgnore didn't work

os/gtime/gtime_time.go, os/gtime/gtime_z_unit_time_test.go
=> feat: :art: some time features.

os/gtime/gtime_sql.go, os/gtime/gtime_z_unit_sql_test.go
=> 为gtime添加scanner和valuer

container/gset/gset_z_example_str_test.go
=> gstrset Example Finish

container/gset/gset_z_example_int_test.go
=> add examples for InitSet of package gset

container/gvar/gvar_z_example_test.go
=> add gvar example

os/gfile/gfile_z_exmaple_basic_test.go
The sample test of gfile example is added. Please review it by Guo da
=> pull request by gfile example

database/gdb/gdb_driver_pgsql.go
Implementing ConvertDataForRecord in DriverPgsql to support pg.Array
=> support manipulate pg.Array type data

database/gdb/gdb_core.go
=> gdb Ping with context

internal/utils/utils_str.go
=> Repeat 'len(s)'.

.github/workflows/gf.yml, contrib/registry/polaris/polaris_test.go, example/registry/polaris/client/main.go, example/registry/polaris/server/main.go
https://github.com/gogf/gf/issues/1866
=> [ISSUE #1866] Fix/polaris logs dir and docker image

net/ghttp/internal/client/client_response.go
fix response close of package gclient
=> fix response close of package gclient

net/ghttp/ghttp_request.go
- update `EnterTime` comment for `ghttp.Request`
- update `LeaveTime` comment for `ghttp.Request`
- <https://github.com/gogf/gf/commit/4c1b4f7858a7959e88076849782de844802774e2>
- <https://github.com/gogf/gf/blob/master/net/ghttp/ghttp_request.go#L85>
- <https://github.com/gogf/gf/blob/master/net/ghttp/ghttp_server_handler.go#L48>
- <https://github.com/gogf/gf/blob/master/net/ghttp/ghttp_server_log.go#L35>
- <https://github.com/gogf/gf/blob/master/net/ghttp/ghttp_server_log.go#L62>
- <https://goframe.org/pages/viewpage.action?pageId=1114174>
=> update comment for ghttp.Request

database/gdb/gdb_model_utility.go
=> fix issue #1965

contrib/drivers/pgsql/pgsql.go
=> fix: pgsql list table names

contrib/nosql/redis/redis_z_group_hash_test.go
test: add redis group hash unit test
=> hash test case completed

database/gdb/gdb.go, database/gdb/gdb_core.go, database/gdb/gdb_core_transaction.go
feature: modify sql count return int64 #2265
=> feat: modify sql count value int64

container/garray/garray_normal_any.go, container/garray/garray_normal_int.go, container/garray/garray_sorted_any.go, container/garray/garray_sorted_int.go, container/gset/gset_any_set.go, container/gset/gset_int_set.go, container/gset/gset_str_set.go, container/gset/gset_z_example_int_test.go, container/gset/gset_z_example_str_test.go, contrib/drivers/sqlite/sqlite.go, encoding/gurl/url.go, net/gclient/gclient_bytes.go, net/gclient/gclient_var.go, net/gclient/gclient_z_example_test.go, net/goai/goai.go, net/gudp/gudp_conn.go, net/gudp/gudp_server.go, os/gspath/gspath.go, os/gtimer/gtimer_queue.go, util/gpage/gpage.go, util/grand/grand_buffer.go, util/gutil/gutil_comparator.go, util/gvalid/gvalid_z_unit_feature_recursive_test.go
=> fix typo for comments

os/gcron/gcron_schedule.go, os/gcron/gcron_z_unit_schedule_test.go, os/gcron/gcron_z_unit_test.go
https://github.com/gogf/gf/issues/2286
=> fix: gcron check if the predefined patterns fail

.github/workflows/gf.yml
https://github.com/gogf/gf/issues/2276
szenius/set-timezone暂时还没支持，等他升级之后再改
=> ci: action update

cmd/gf/internal/cmd/cmd_run.go
https://github.com/gogf/gf/issues/2383
=> fix issue in `gf run` failed with arguments passed in windows platform

net/ghttp/ghttp_request_param.go
https://github.com/gogf/gf/issues/2261
=> fix issue #2261

README.MD, cmd/gf/internal/cmd/cmd_build.go, cmd/gf/internal/cmd/genservice/genservice_generate.go, container/gset/gset_z_unit_any_test.go, container/gset/gset_z_unit_int_test.go, container/gset/gset_z_unit_str_test.go, contrib/drivers/clickhouse/clickhouse_test.go, contrib/nosql/redis/redis_group_list.go, contrib/nosql/redis/redis_group_set.go, contrib/nosql/redis/redis_group_string.go, encoding/gjson/gjson_z_example_test.go, internal/deepcopy/deepcopy_test.go, net/gtcp/gtcp_z_unit_test.go, os/gcron/gcron_z_unit_schedule_test.go, util/gconv/gconv_z_unit_slice_test.go, util/gutil/gutil_z_unit_dump_test.go
具体看
https://goreportcard.com/report/github.com/gogf/gf/v2
=> fix goreport for gofmt

net/ghttp/ghttp.go, net/ghttp/ghttp_request.go, net/ghttp/ghttp_request_middleware.go, net/ghttp/ghttp_request_param_ctx.go
It then can retrieve the context from custom http server handler.
=> update context of the original http request

contrib/nosql/redis/redis.go
Fix the issue that Redis maxConnLifetime parameter not working.
Fixes #2775.
=> fix issue #2775

cmd/gf/internal/cmd/genctrl/genctrl_generate_sdk.go
=> fix `gen ctrl` import path

net/ghttp/ghttp_server_service_handler.go, net/ghttp/ghttp_z_unit_feature_router_strict_test.go
=> fix generic check with slice for ghttp

contrib/drivers/mysql/mysql_feature_model_join_test.go, database/gdb/gdb_model_join.go
=> ORM add function: LeftJoinOnFields,RightJoinOnFields,InnerJoinOnFields

net/ghttp/ghttp_z_unit_feature_middleware_basic_test.go
=> delete repeat code in ut for package ghttp

contrib/registry/nacos/nacos_watcher.go, contrib/registry/nacos/nacos_z_test.go
Fix the cpu will be full when nacos call proceed.
=> fix issue #3100 

util/gconv/gconv_struct.go, util/gconv/gconv_z_unit_converter_test.go
=> fix issue #3099

cmd/gf/internal/cmd/genenums/genenums_parser.go
enhance #3129 
`genenums package` init function can load all `std pageage`. This leads to `gf command` running slowly for the first time.
genenums  包的init函数会 pageckes.load 所有的 go 标准包，导致gf命令在首次运行时十分缓慢
=> enhance #3129

cmd/gf/internal/cmd/cmd_build.go
=> fix issue in cross-building failed in windows

contrib/drivers/pgsql/pgsql.go
=> fix: #2967

net/ghttp/ghttp_server_admin_process.go
=> fix: #3179

net/ghttp/ghttp_server_handler.go, net/ghttp/ghttp_z_unit_feature_session_test.go
=> fix: #2689 change sessionId in cookie

util/gconv/gconv_map.go, util/gconv/gconv_z_unit_map_test.go
bugfix:fix gconv map deep option not effective
=> bugfix:fix gconv map deep option not effective

i18n/gi18n/gi18n_manager.go
fix error code comment on i18n defaultLanguage value
=> fix error code comment on i18n defaultLanguage value

contrib/drivers/dm/dm_z_unit_basic_test.go, contrib/drivers/dm/dm_z_unit_init_test.go
`update` 字段也会出现和 `create` 相同的问题
=> fix: unit test of dm failed occasionally

util/gvalid/gvalid_z_unit_feature_rule_test.go, util/gvalid/internal/builtin/builtin_enums.go
=> util/gvalid: fix slice enums verification failed

container/gtree/gtree.go, container/gtree/gtree_avltree.go, container/gtree/gtree_z_example_avltree_test.go
**Dear reviewer:**
使用 `goda` 重构 `avltree`，并且新增 `gtree interface`，用做规范
=> refractor(container/gtree): refactor code with gods package for avltree

.github/workflows/sonarcloud.yaml, sonar-project.properties
**Please ensure you adhere to every item in this list.**
+ The PR title is formatted as follows: `<type>[optional scope]: <description>` For example, `fix(os/gtime): fix time zone issue`
+ `<type>` is mandatory and can be one of `fix`, `feat`, `build`, `ci`, `docs`, `style`, `refactor`, `perf`, `test`, `chore`
+ fix: Used when a bug has been fixed.
+ feat: Used when a new feature has been added.
+ build: Used for modifications to the project build system, such as changes to dependencies, external interfaces, or upgrading Node version.
+ ci: Used for modifications to continuous integration processes, such as changes to Travis, Jenkins workflow configurations.
+ docs: Used for modifications to documentation, such as changes to README files, API documentation, etc.
+ style: Used for changes …
=> ci: add Scorecard workflow

database/gdb/gdb_core_config.go, database/gdb/gdb_z_mysql_internal_test.go
=> fix(database/gdb): #3755 error parsing database link without port number

net/ghttp/ghttp_server.go, net/ghttp/ghttp_server_admin.go, net/ghttp/ghttp_server_admin_process.go, net/ghttp/ghttp_server_config.go, net/ghttp/ghttp_server_config_api.go, net/ghttp/ghttp_server_config_mess.go, net/ghttp/ghttp_server_graceful.go, net/ghttp/ghttp_z_unit_feature_config_test.go
=> fix(net/ghttp): server shutdown not graceful using admin api `/debug/admin/shutdown`

contrib/drivers/pgsql/pgsql_do_filter.go, contrib/drivers/pgsql/pgsql_do_insert.go, contrib/drivers/pgsql/pgsql_z_unit_db_test.go
pgsql insert or ignore support
=> feat(contrib/drivers/pgsql): add InsertIgnore support

net/gclient/gclient.go, net/gclient/gclient_z_unit_test.go
=> fix(net/gclient): Client Clone with allocated header/cookie

contrib/drivers/pgsql/pgsql_open.go
fix: https://github.com/gogf/gf/issues/3899
=> fix(contrib/drivers/pgsql): connection fails when postgres database password is empty

README.MD
=> chore: update README.MD

cmd/gf/internal/cmd/testdata/build/varmap/go.sum, go.mod, go.sum
https://github.com/fsnotify/fsnotify/pull/653
=> build: downgrade fsnotify from v1.8.0 to v1.7.0 to solve data race error

cmd/gf/internal/cmd/cmd_doc.go
=> feat(cmd/gf): change document source from repo `gf` to `gf-site`

contrib/registry/zookeeper/zookeeper_registrar.go, contrib/registry/zookeeper/zookeeper_watcher.go
=> fix(registry/zookeeper): watch service name path error with extra suffix `-`

net/goai/goai_shema.go, net/goai/goai_z_unit_issue_test.go
fix: https://github.com/gogf/gf/issues/3930
=> fix(net/goai): embedded struct with tags also expand as properties of the parent struct

net/goai/goai.go, net/goai/goai_shema_ref.go, net/goai/goai_z_unit_issue_test.go
fix: https://github.com/gogf/gf/issues/3235
=> feat(net/goai): support OpenAPIv3.1 in description field for schema object

net/ghttp/ghttp_z_unit_issue_test.go, net/ghttp/internal/response/response_buffer_writer.go
fix https://github.com/gogf/gf/issues/4115
=> fix(net/ghttp): BufferWriter.Flush writes additional information after custom response wrote

.github/workflows/ci-main.sh, net/ghttp/ghttp_request.go, net/ghttp/ghttp_z_unit_feature_request_test.go, os/gstructs/gstructs.go, util/gmeta/gmeta.go
=> feat(net/ghttp): add `Request.GetMetaTag` to retrieve specific meta tag value

net/ghttp/ghttp_request.go, net/ghttp/ghttp_z_unit_feature_request_test.go
=> feat(net/ghttp): enhance GetHeader method to support default values

net/ghttp/ghttp_request_param.go
1. When uploading binary data, the body should not be formatted; otherwise, it may cause excessive memory usage.
=> feat(net/ghttp): skip binary contentType when parseBody

util/gvalid/testdata/i18n/cn/validation.toml
Fix spacing in min value validation message
=> fix: spacing in min value validation message

net/gclient/gclient.go
**Please ensure you adhere to every item in this list.**
+ The PR title is formatted as follows: `<type>[optional scope]: <description>` For example, `fix(os/gtime): fix time zone issue`
+ `<type>` is mandatory and can be one of `fix`, `feat`, `build`, `ci`, `docs`, `style`, `refactor`, `perf`, `test`, `chore`
+ `fix`: Used when a bug has been fixed.
+ `feat`: Used when a new feature has been added.
+ `build`: Used for modifications to the project build system, such as changes to dependencies, external interfaces, or upgrading Node version.
+ `ci`: Used for modifications to continuous integration processes, such as changes to Travis, Jenkins workflow configurations.
+ `docs`: Used for modifications to documentation, such as changes to README files, API documentation, etc.
+ `style`: Used …
=> perf(net/gclient): optimize default http.Transport connection pool configuration

.github/workflows/scripts/update_version.sh, .github/workflows/tag.yml, .make_version.sh, README.MD, contrib/registry/nacos/go.mod
=> fix: #4269

container/gqueue/gqueue.go, container/gqueue/gqueue_z_unit_test.go
=> fix(container/gqueue): Optimize queue length calculation and loop structure in test cases

cmd/gf/internal/cmd/gendao/gendao.go
Add "*" and "?" to tableEx for "gf gen dao".
The "*" will match none or some char. And the "?" only match one char.
=> feat(cmd/gf): add broad matching to gf gen dao's tableEx attribute.
